version: "3"
services:
  copy_paste:
    build:
      context: .
    working_dir: /home/pwn
    container_name: copy_paste
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9009:9000"
    entrypoint: /etc/init.sh
