version: "3"
services:
  bstack:
    build:
      context: .
    working_dir: /home/pwn
    container_name: timetable
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9008:9000"
    entrypoint: /etc/init.sh
