version: "3"
services:
  netcat:
    build:
      context: .
    working_dir: /home/pwn
    container_name: netcat
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9001:9000"
    entrypoint: /etc/init.sh
