[package]
name = "hanko"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "fs", "process"] }
tracing = "0.1"
tracing-subscriber = "0.3"
hyper = "0.14"
tower-http = { version = "0.3", features = ["trace"] }
axum = { version = "0.6", features = ["macros", "multipart"] }
bytes = "1"
uuid = { version = "1", features = ["v4", "serde"] }
