version: "3"
services:
  ret2win:
    build:
      context: .
    working_dir: /home/pwn
    container_name: ret2win
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9003:9000"
    entrypoint: /etc/init.sh
